name: Auto Update & Deploy

on:
  workflow_dispatch:  # Allows manual run from GitHub UI
  schedule:
    - cron: '30 22 * * *'  # Optional: run daily at 6am UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 mplsoccer matplotlib seaborn scipy

      - name: Run Data Scripts
        run: |
          python data/data_scraper_script.py
          python data/data_loader.py

      - name: Commit & Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f static/shotmaps/team
          git add -f static/shotmaps/all
          git add -f static/heatmaps
          git add -f data/tables
          git commit -m "🔁 Auto update: fixtures, shotmaps, heatmaps, league tables" || echo "No changes to commit"
          git push origin main
